import { Libre_Baskerville, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-libre",
});

export const metadata = {
  title: "Learning Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${libreBaskerville.variable} antialiased`}
      >
        <header className="py-2 md:w-8/12 mx-auto">
          <Navbar className="font-libre"></Navbar>
        </header>

        <main>{children}</main>

        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
